### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by kattjevfel** [jbruchon/libjodycode#1]
Hi, since this was added as a dependency for jdupes I am now trying to package this for Arch Linux, it builds just fine but  `make install` fails even outside of pacman etc:

```
katt@main build/libjodycode (master) » make DESTDIR=test install        
cc -shared -o libjodycode.so cacheinfo.o jody_hash.o oom.o paths.o sort.o string.o string_malloc.o strtoepoch.o version.o win_stat.o win_unicode.o 
ar rcs libjodycode.a cacheinfo.o jody_hash.o oom.o paths.o sort.o string.o string_malloc.o strtoepoch.o version.o win_stat.o win_unicode.o 
make: *** [Makefile:99: installdirs] Error 1
```

This happens both to git master (447b21fec0376f05e02b5ace43934e10d4b9ca20) and v1.0

gcc 12.2.1
make 4.41

Please inform me if I need to provide any more details.

**Comment by kattjevfel** [comment]
Yes that works perfectly, thanks for the quick fix! :)

**Comment by jbruchon** [comment]
I'm always happy to help. If Arch has winregfs I've also added this library as a dependency in the latest master. Don't know who needs to know that though.
