### ISSUE TITLE
built for arm systems?

### ISSUE THREAD

**Issue by rezad1393** [jbruchon/libjodycode#5]
I am trying to build the new version (v2) on my arm system (aur package on archlinux) and I get this error.
```
cc: error: unrecognized command-line option ‘-mavx2’
make: *** [Makefile:114: jody_hash_simd.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'libjodycode-2.0-1': 

```

can this be fixed or I no longer can use this app on arm?

**Comment by rezad1393** [comment]
> Fetch the latest code from here and build it. I did some Makefile fixes that should fix the problem.

thank you.
I will try the next update on archlinux aur.

**Comment by jbruchon** [comment]
FYI I am trying to work with Arch to get my latest Makefile changes added. https://aur.archlinux.org/packages/libjodycode#comment-914377

**Comment by rezad1393** [comment]
> FYI I am trying to work with Arch to get my latest Makefile changes added. https://aur.archlinux.org/packages/libjodycode#comment-914377

can you tell them to add armv7l to PKGBUILD so that pikaur doesnt ask me if I am sure that I want to build it for arm?
I have odroid xu4 which is a arm32(armv7l).
