### ISSUE TITLE
libjodycode.7 is empty

### ISSUE THREAD

**Issue by eribertomota** [jbruchon/libjodycode#6]
As said in the tittle.

**Comment by jbruchon** [comment]
I haven't written it yet. I may be making some more major changes and putting out a 3.0 API first. There's also another library component I need to add. I'm not quite ready to document it all for use by others yet. Do you have any suggestions about some things to cover?

**Comment by eribertomota** [comment]
Thanks for your quick reply. I have no suggestions. I am packaging it for Debian to support jdupes 1.23.0 and this issue was pointed from lintian. I will disable the manpage install.

**Comment by jbruchon** [comment]
There is now a suitable basic man page for libjodycode!
