### ISSUE TITLE
Build process on Debian fails when running 'make test'

### ISSUE THREAD

**Issue by eribertomota** [jbruchon/libjodycode#7]
Hi @jbruchon,

When building a package, Debian always run 'make test' via 'dh_auto_test'. I am getting the following error:

```
   dh_auto_test
        make -j16 test
make[1]: Entering directory '/PKGS/libjdupes/libjodycode-2.0.1'
./test.sh
make[1]: ./test.sh: No such file or directory
```

I am disabling dh_auto_test to avoid a FTBFS (Fail To Build From Source).

**Comment by jbruchon** [comment]
That's probably because I copied the Makefile from jdupes and then edited it. I can remove the rule for now, or write a dummy script if that'll help.

**Comment by jbruchon** [comment]
I am willing to do a new point release that includes a very basic man page and a dummy test script if that will help you out.

**Comment by eribertomota** [comment]
Don't worry. I am only reporting the issues. The package is working fine because I am fixing the issues. Take your time.

**Comment by jbruchon** [comment]
I've added a dummy script and a basic man page in 1b4f15c6eb5fc0d33f351e225edf61f7bbd69d70 which will be included in the next release.

**Comment by eribertomota** [comment]
Thanks!

**Comment by eribertomota** [comment]
However... I have a problem here... 
```

# objdump -x debian/libjodycode2/usr/lib/x86_64-linux-gnu/libjodycode.so.2 | grep SONAME
  SONAME               libjodycode.so.2
```

Considering that SONAME is libjodycode.so.2, the package name on Debian must be libjodycode2. Consequently, IMO, the manpage should be libjodycode2.7.

**Comment by eribertomota** [comment]
Ah, the jdupes has the same problem: make test returns `make[1]: ./test.sh: No such file or directory`.

**Comment by jbruchon** [comment]
I just fixed it the same way: adding the same dummy script. Also, to address two other things:

1. If I make the man page title contain the library major version then the library itself should also carry that major version, complicating builds both here and in the programs that link to it (I test all my software using `make USE_NEARBY_JC=1 static_jc` which relies on the exact files `../libjodycode/libjodycode.{h,a}` existing). I'm not ready to go full autoconf and pkg-config right now. I have written a simple helper program to make this easier to script; try `make apiver` out.
2. Unrelated to libjodycode, I've come up with a great way to fix the long-standing inconsistent output order issue in jdupes that's much less intrusive than what I feared I'd need to do. I'll be making that my top priority for my next code run.

**Comment by eribertomota** [comment]
> I just fixed it the same way: adding the same dummy script. Also, to address two other things:


Thanks!!!


>     1. If I make the man page title contain the library major version then the library itself should also carry that major version, complicating builds both here and in the programs that link to it (I test all my software using `make USE_NEARBY_JC=1 static_jc` which relies on the exact files `../libjodycode/libjodycode.{h,a}` existing). I'm not ready to go full autoconf and pkg-config right now. I have written a simple helper program to make this easier to script; try `make apiver` out.


Ok, I will check this in next revision.

 
>     2. Unrelated to libjodycode, I've come up with a great way to fix the long-standing inconsistent output order issue in jdupes that's much less intrusive than what I feared I'd need to do. I'll be making that my top priority for my next code run.

Hummm. Will this solve the issue about non-reprocible builds? If yes, very good!
