### ISSUE TITLE
Debian: lintian warns about exit-in-shared-library

### ISSUE THREAD

**Issue by eribertomota** [jbruchon/libjodycode#8]
From lintian:

```
X: libjodycode2: exit-in-shared-library [usr/lib/x86_64-linux-gnu/libjodycode.so.2.0.1]
N: 
N:   The listed shared library calls the C library exit() or _exit() functions.
N:   
N:   In the case of an error, the library should instead return an appropriate error code to the calling
N:   program which can then determine how to handle the error, including performing any required clean-up.
N:   
N:   In most cases, removing the call should be discussed with upstream, particularly as it may produce an
N:   ABI change.
```

This is an experimental warning. Feel free to close this issue if you think that this is not important.

**Comment by jbruchon** [comment]
This is actually a huge reason I'm going to put out a 3.0 API. It shouldn't be doing exit calls but everything I have written expects it.

**Comment by eribertomota** [comment]
Ok!

**Comment by jbruchon** [comment]
I've removed all the `exit()` calls for API 3 except for the ones in `oom.c`--the purpose of the code in OOM is memory-related error exits (out-of-memory and NULL pointers). Is there some way I can tell Debian that the exits are OK?

**Comment by eribertomota** [comment]
> I've removed all the `exit()` calls for API 3 except for the ones in `oom.c`--the purpose of the code in OOM is memory-related error exits (out-of-memory and NULL pointers). Is there some way I can tell Debian that the exits are OK?

No way to tell it to Debian. However, this is a minor warning from Lintian and your work seems fine. No worries.
